spring.application.name=resumebuilderapi
spring.datasource.url=jdbc:mysql://localhost:3306/resume_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Email configuration
# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dharmendraram7852@gmail.com
spring.mail.password=rjazdpvsbpgmycqv
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Sender email
spring.mail.properties.mail.smtp.from=dharmendraram7852@gmail.com

#Application info
app.base.url= http://localhost:8080

#Cloudinary information
cloudinary.cloud_name=dnbxpx9q
cloudinary.api_key=216373153441456
cloudinary.api_secret=epV5W2-3KGiIkegG3ibnYJZqgBo

# Jwt Configuration
jwt.secret=resumebuilder_super_secret_jwt_key_2024_secure_256bit_key!!
jwt.expiration=604800000

# eSewa ePay v2 configuration
esewa.product-code=EPAYTEST
esewa.secret-key=8gBm/:&EnhH.1/q(
esewa.payment-url=https://rc-epay.esewa.com.np/api/epay/main/v2/form
esewa.status-url=https://uat.esewa.com.np/api/epay/transaction/status/
esewa.success-url=http://localhost:8080/api/payment/verify
esewa.failure-url=http://localhost:8080/api/payment/failure
premium.plan.amount=1000
